<a href="https://colab.research.google.com/github/genggengi/AI/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY ndarray(N-Dimensional Arrays)重要屬性:shape dimension

軸 (axis) 與維度 (dimension)
shape
dtype 屬性

In [2]:
import numpy as np
ar2=np.array([[0,3,5],[2,8,7]])
# ar2.shape
ar2.ndim

2

ndarray資料型態(dtype)與型態轉換(astype)

In [3]:
ar=np.array([2,4,6,8]); 
ar.dtype

dtype('int64')

下列程式執行後的結果為何?

In [4]:
f_ar = np.array([13,-3,8.88])
f_ar

intf_ar=f_ar.astype(int)
intf_ar

array([13, -3,  8])

[3]單一Numpy ndarray的各種運算
建立array(陣列)的方式與實作(有許多方式)
1.使用Python內建的array()建立陣列
2.使用numpy提供的創建函數建立陣列
3.直接生成==>使用genfromtxt()方法建立陣列[進階,初學可略過]

1.使用Python內建的array()建立陣列

In [8]:
import numpy as np
x = np.array([[1,2.0],[0,0],(1+1j,3.)])

2.使用numpy提供的創建函數建立陣列

In [9]:
import numpy as np
ar9 = np.eye(3);
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

使用np.zeros建立陣列

In [10]:
import numpy as np
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

使用np.ones建立陣列

In [11]:
import numpy as np
np.ones((4, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

使用np.arange建立陣列

In [12]:
import numpy as np
np.arange(2, 3, 0.1) # start, end, step

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

使用np.linspace建立陣列

In [13]:
import numpy as np
np.linspace(1., 4., 6) # start, end, num

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

使用np.linspace建立陣列

In [14]:
import numpy as np
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

使用np.linspace建立陣列

In [15]:
import numpy as np
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

使用np.linspace建立陣列

In [16]:
import numpy as np
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

使用np.indices建立陣列

In [17]:
import numpy as np
np.indices((3, 3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

使用np.diag建立陣列

In [18]:
import numpy as np
ar10=np.diag((2,1,4,6));
ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [19]:
import numpy as np
a = np.array([0, 1, 2])
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [20]:
import numpy as np
a = np.array([0, 1, 2])
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [21]:
import numpy as np
a = np.array([0, 1, 2])
np.tile(a, (2, 1, 2))

array([[[0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2]]])

3.直接生成使用genfromtxt()方法建立陣列[進階,初學可略過]

In [22]:
import csv
import numpy as np

x = '''1,3,2,3,1,2,3,4
2,4,5,0.6,5,6,7,8
3,7,8,9,9,10,11,12
4,1,1.1,1.2,13,14,15,16
'''
with open("abc.txt",mode="w",encoding="utf-8") as file:
  file.write(x)
file.close()

np.genfromtxt('abc.txt', delimiter=',', invalid_raise = False)


array([[ 1. ,  3. ,  2. ,  3. ,  1. ,  2. ,  3. ,  4. ],
       [ 2. ,  4. ,  5. ,  0.6,  5. ,  6. ,  7. ,  8. ],
       [ 3. ,  7. ,  8. ,  9. ,  9. , 10. , 11. , 12. ],
       [ 4. ,  1. ,  1.1,  1.2, 13. , 14. , 15. , 16. ]])

下列程式執行後的結果為何?

In [23]:
import numpy as np
np.tile(np.array([[1,2],[6,7]]),3)

array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

In [24]:
np.tile(np.array([[1,2],[6,7]]),3)
import numpy as np
np.tile(np.array([[1,2],[6,7]]),(2,2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

下列程式執行後的結果為何?

In [25]:
import numpy as np
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [26]:
import numpy as np
np.tile(np.array([[1,2],[6,7]]),3)

array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

In [27]:
import numpy as np
np.tile(np.array([[1,2],[6,7]]),(2,2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

NUMPY ndarray 運算(Array shape manipulation)

reshape
ravel()
T
newaxis

reshape

In [29]:
import numpy as np
x = np.arange(2,10).reshape(2,4)
x

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [30]:
import numpy as np
y = np.arange(2,10).reshape(4,2)
y

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

ravel

In [31]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(10,15)]); 
ar

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [32]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(10,15)])
ar.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

T

In [33]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(10,15)])
ar.T

array([[ 1, 10],
       [ 2, 11],
       [ 3, 12],
       [ 4, 13],
       [ 5, 14]])

newaxis

In [34]:
import numpy as np
ar=ar[:, np.newaxis]; ar.shape
ar

array([[[ 1,  2,  3,  4,  5]],

       [[10, 11, 12, 13, 14]]])

下列程式執行後的結果為何?

In [35]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(10,15)])
ar.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

In [36]:
import numpy as np
ar=np.array([14,15,16])
ar=ar[:, np.newaxis]
ar.shape

(3, 1)

ndarray的索引(index)與切片運算(slice)
1.索引(index)

In [37]:
import numpy as np
x = np.arange(2,10)
# x
print(x[0])
print(x[-2])
print(x[-1])

2
8
9


In [38]:
import numpy as np
ar = np.array([[2,3,4],[9,8,7],[11,12,13]])
ar[1,2]

7

2.切片運算(slice)

In [39]:
import numpy as np
ar=2*np.arange(6)
# ar
ar[1:5:2]

array([2, 6])

In [40]:
import numpy as np
ar=2*np.arange(6)
# ar
ar[1:6:2]

array([ 2,  6, 10])

In [41]:
import numpy as np
ar=2*np.arange(6)
# ar
ar[:4]

array([0, 2, 4, 6])

[小測驗]下列程式執行後的結果為何?

In [43]:
import numpy as np
ar = np.array([[2,3,4],[9,8,7],[11,12,13]])
# ar
ar[2,:] 

array([11, 12, 13])

In [44]:
import numpy as np
ar = np.array([[2,3,4],[9,8,7],[11,12,13]])
# ar
ar[:,1]  

array([ 3,  8, 12])

In [45]:
import numpy as np
ar = np.array([[2,3,4],[9,8,7],[11,12,13]])
# ar
ar[2,-1]

13

In [46]:
import numpy as np
ar=2*np.arange(6)
# ar
ar[::3]

array([0, 6])

In [47]:
import numpy as np
ar=2*np.arange(6)
# ar
ar[:3]=1
ar

array([ 1,  1,  1,  6,  8, 10])

In [48]:
import numpy as np
ar=2*np.arange(6)
# ar
ar[2:]=np.ones(4)
ar

array([0, 2, 1, 1, 1, 1])

ndarray的Reduction 運算:prod()|sum()|mean()|median()

prod()
sum()
mean()
median(ar)

In [50]:
import numpy as np
ar=np.arange(1,5)
ar.prod()

24

In [51]:
import numpy as np
ar=np.array([[2,3,4],[5,6,7],[8,9,10]])
ar.sum()

54

In [52]:
import numpy as np
ar=np.array([[2,3,4],[5,6,7],[8,9,10]])
ar.mean()

6.0

In [53]:
import numpy as np
ar=np.array([[2,3,4],[5,6,7],[8,9,10]])
np.median(ar)

6.0

[小測驗]下列程式執行後的結果為何?

In [54]:
ar=np.array([np.arange(1,6),np.arange(1,6)])
# ar
np.prod(ar,axis=0)

array([ 1,  4,  9, 16, 25])

In [55]:
ar=np.array([np.arange(1,6),np.arange(1,6)])
# ar
np.prod(ar,axis=1)

array([120, 120])

[5]多Numpy ndarray的各種運算(A矩陣與B矩陣間的運算)
加法運算


In [56]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
# arr
arr+arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

乘法運算

In [57]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
# arr
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [58]:
import numpy as np
ar=np.array([[1,1],[1,1]])
ar2=np.array([[2,2],[2,2]])
ar*ar2

array([[2, 2],
       [2, 2]])

dot運算

In [59]:
import numpy as np
ar=np.array([[1,1],[1,1]])
ar2=np.array([[2,2],[2,2]])
ar.dot(ar2)

array([[4, 4],
       [4, 4]])

[小測驗]下列程式執行後的結果為何?

In [60]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
# arr
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
# arr
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [62]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
# arr
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [63]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [64]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

[6]ndarray 運算的Broadcasting(廣播機制)

In [65]:
import numpy as np
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [66]:
import numpy as np
np.arange(3) + 5

array([5, 6, 7])

In [67]:
import numpy as np
np.ones((3, 3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

[小測驗]下列程式執行後的結果為何?

In [68]:
import numpy as np
np.arange(3).reshape((3, 1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

[7]自主學習主題
使用<Numpy random模組>產生隨機資料
numpy.random.randint(low, high=None, size=None, dtype='l')

seed
random.randint

In [69]:
import numpy as np
np.random.randint(1,5)

2

In [70]:
import numpy as np
np.random.randint(-5,5,size=(2,2))

array([[-2, -2],
       [-5,  2]])

In [71]:
import numpy as np
np.random.seed(0)
x1 = np.random.randint(10, size=6) 
x1

array([5, 0, 3, 3, 7, 9])

In [72]:
import numpy as np
np.random.seed(0)
x2 = np.random.randint(10, size=(3, 4))
x2

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [73]:
import numpy as np
np.random.seed(0)
x3 = np.random.randint(10, size=(3, 4, 5))
x3

array([[[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1],
        [6, 7, 7, 8, 1]],

       [[5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1]],

       [[9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6],
        [8, 4, 1, 4, 9]]])

[小測驗]下列程式執行後的結果為何?

In [74]:
import numpy as np
np.random.randint(1,size=5)

array([0, 0, 0, 0, 0])

NUMPY ndarray 運算(A矩陣與B矩陣間的convolute運算)[進階,初學可略過]

numpy.convolve(a, v, mode=‘full’ )

convolve

In [76]:
import numpy as np
np.convolve([1, 2, 3], [0, 1, 0.5])

array([0. , 1. , 2.5, 4. , 1.5])

In [77]:
import numpy as np
np.convolve([1,2,3],[0,1,0.5], 'same')

array([1. , 2.5, 4. ])

In [78]:
import numpy as np
np.convolve([1,2,3],[0,1,0.5], 'same')
import numpy as np
np.convolve([1,2,3],[0,1,0.5], 'valid')

array([2.5])

[小測驗]下列程式執行後的結果為何?

In [79]:
import numpy as np
np.convolve([1, 2, 3], [0, 1, 0.5])

array([0. , 1. , 2.5, 4. , 1.5])

NUMPY ndarray(N-Dimensional Arrays)檔案輸入與輸出
https://ithelp.ithome.com.tw/articles/10196167
save()
load()

NUMPY ndarray 運算 - 排序sort[進階,初學可略過]
https://github.com/femibyte/mastering_pandas/blob/master/MasteringPandas-chap3_DataStructures.ipynb

學生報告:舉例說明numpy陣列的各項排序運算

sort

In [80]:
import numpy as np
ar=np.array([[3,2],[10,-1]])
# ar
ar.sort(axis=1)
ar

array([[ 2,  3],
       [-1, 10]])

[小測驗]下列程式執行後的結果為何?

In [81]:
import numpy as np
ar=np.array([[3,2],[10,-1]])
# ar
ar.sort(axis=0)
ar

array([[ 3, -1],
       [10,  2]])

In [82]:
import numpy as np
ar=np.random.randint(10,size=5)
ar.sort()
ar[::-1]

array([9, 8, 7, 1, 1])

龍大大 我的億 大樂透 開獎中心
說明底下程式的處理邏輯

In [83]:
import random as rand

list1 = rand.sample(range(1,50), 7)

special = list1.pop()

list1.sort()

print("龍大大 我的億 大樂透 開獎中心")
print("本期大樂透中獎號碼為：", end="")
for i in range(0,6):
    if i == 5:    print(str(list1[i]))
    else:    print(str(list1[i]), end=", ")
print("本期大樂透特別號為：" + str(special))

龍大大 我的億 大樂透 開獎中心
本期大樂透中獎號碼為：26, 27, 32, 40, 44, 45
本期大樂透特別號為：20


說明底下程式的處理邏輯

[1]產生從1到49的7個不重複的整數

[2]設定中獎號法
挑出一個當作 特別號
剩下六個當作 中獎號碼

[3]印出 特殊格式輸出 的 中獎單